---
version: '3.9'
services:
  datetime:
    build:
      context: ./
      dockerfile: dev/docker/services/php/Dockerfile
      args:
        GITHUB_TOKEN: "${GITHUB_TOKEN?err}"
    environment:
      GITHUB_TOKEN: "${GITHUB_TOKEN?err}"
    volumes:
      - ./:/Shrikeh/DateTime
